### ISSUE TITLE
Compare snapshots feature is not working

### ISSUE THREAD

**Issue by qtoulou** [o19s/quepid#789]
**Describe the bug**
When I click on "Compare snapshots" to compare the current version with a previous stored one, I only have question mark in place of all the scores of the snapshot results. Same for the overall score which has a question mark instead. (See the screenshot below )

**To Reproduce**
1. Go to app.quepid
2. Create a test
3. Run the searches and create a snapshot
4. Run the searches again and compare with your previous snapshot 

**Expected behavior**
I expect to see for all the results, the current score as it is and the scores from the snapshots to be able to compare.

**Screenshots**

![image](https://github.com/o19s/quepid/assets/99342432/037d40bc-b8fb-4161-8c95-2165f076e30d)

**Comment by epugh** [comment]
I've pushed this fix to app.quepid.com if you want to test it...

**Comment by qtoulou** [comment]
> I've pushed this fix to app.quepid.com if you want to test it...

Thank you @epugh. Unfortunately, I still have the issue. Do I have to configure anything in order to get this fix ?

**Comment by epugh** [comment]
Humm....    No, if you use app.quepid.com it should work.  I think we should jump on Zoom next week, let's connect via Slack.

**Comment by hussainqp** [comment]
Hi @epugh , is this issue fixed? Still seeing the same:
![Uploading image.png…]()

**Comment by epugh** [comment]
Hi, we've had significant reworking of snapshots, and I'm hopeful your issue is solved..  would you be able to test again and provide an update?

**Comment by epugh** [comment]
There is a ton of work just shipped in Quepid 7.15.0 that fixes this.
